parser: typescript
printWidth: 120
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: es5
bracketSameLine: false
arrowParens: avoid
endOfLine: lf

overrides:
  - files: "**/*.css"
    options:
      parser: css
      tabWidth: 4